import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import * as stylex from "@stylexjs/stylex";

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] }); does not work with stylex

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DARK = "@media (prefers-color-scheme: dark)";

const styles = stylex.create({
  html: {
    fontFamily: "system-ui, sans-serif",
    backgroundColor: "white",
    color: "black",
    [DARK]: {
      backgroundColor: "black",
      color: "white",
    },
  },
  reset: {
    minHeight: "100%",
    margin: 0,
    padding: 0,
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html {...stylex.props(styles.html, styles.reset)} lang="en">
      <body {...stylex.props(styles.reset)}>{children}</body>
    </html>
  );
}
